version: "3"
services:
  app:
    container_name: gebeya_api_exam
    restart: always
    build: .
    ports:
      - 5000:5000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
